name: Enforce Dart format
description: |
  This action will run `dart format` and make sure that no changes
  are necessary - meaning that the code is formatted well
inputs:
  path:
    description: File or directory to check
    required: false
    default: "."
runs:
  using: composite
  steps:
    - name: Run dart format & report errors
      shell: bash
      run: |
        export CHANGES_SUMMARY=$(dart format -o none "${{ inputs.path }}" | grep 'Changed')
        echo $CHANGES_SUMMARY | sed "s/Changed \(.*\)/::error file=\1,title=File has formatting errors::Use \`dart format\` keep code in consistent style./"
        if [[ ! -z "$CHANGES_SUMMARY" ]]; then exit 1; fi