name: Get .env file from Vault
description: |
  This action will fetch a key-value secret from Hashicorp Vault
  and creates an .env file from the items.
inputs:
  secret-path:
    description: "Full path to the secret data"
    required: true
  vault-token:
    description: "Vault token for authentication"
    required: true
  vault-addr:
    description: "Vault server address"
    required: false
    default: "https://vault.sys.dronetag.app"
runs:
  using: "node20"
  main: "main.js"
