name: Authenticate Docker to ECR + ghcr.io
description: |
  This action does the Docker set-up and authenticates to both ECR (Elastic
  Container Registry) and GHCR (Github Container Registry)
inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  aws-region:
    description: AWS Region
    required: false
    default: "eu-north-1"
  github-token:
    description: GitHub Token to authorize to ghcr.io
    required: false
outputs:
  registry: 
    description: AWS registry name
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Authorize Docker to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
