name: Build & push to Azure Container Registry

# Builds an image using the project's Dockerfile, and pushes it
# to ACR (Azure Container Registry) repository.

on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false
        default: latest
      repository-name:
        type: string
        required: true
    secrets:
      github-token:
        required: true
      acr-login-server:
        required: true
      acr-username:
        required: true
      acr-password:
        required: true
      build-args:
        required: false

jobs:
  build:
    name: Build & push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: ./.github/actions/build-push-acr/action.yaml