name: Check delivery

# Checks if a delivery results exists for the version specified

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      awsRegion:
        type: string
        required: false
        default: "eu-north-1"
    secrets:
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true

jobs:
  check:
    name: Check image existence
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.tag }}
      repositoryUri: ${{ steps.release.outputs.repository_uri }}
      awsAccountId: ${{ steps.aws.outputs.aws-account-id }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with: { fetch-depth: 0 } # Required to fetch with tags
      - id: aws
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ inputs.awsRegion }}
          mask-aws-account-id: false
      - id: release
        name: Check release existence
        uses: dronetag/gha-shared/.github/actions/ecr-check-image@master
        with:
          repository: ${{ inputs.repository }}