name: Check delivery

# A pre-deployment check which looks for a successful delivery
#
# This check makes sure that the deployment step can be performed. It makes
# sure that the Delivery workflow has been successful, and checks if the
# actual image exists on ECR.

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: "eu-north-1"
    secrets:
      github-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    outputs:
      version:
        description: Determined (or used) version of delivery
        value: ${{ jobs.check-image.outputs.version }}

jobs:
  check-image:
    name: Check image existence
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.tag }}
      repositoryUri: ${{ steps.release.outputs.repository_uri }}
      awsAccountId: ${{ steps.aws.outputs.aws-account-id }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with: { fetch-depth: 0 } # Required to fetch with tags
      - id: aws
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: false
      - id: release
        name: Check release existence
        uses: dronetag/gha-shared/.github/actions/ecr-check-image@master
        with:
          repository: ${{ inputs.repository }}

  check-workflow:
    name: Check that previous delivery was successful
    runs-on: ubuntu-latest
    steps:
      - name: Check previously run workflow
        uses: dronetag/gha-shared/.github/actions/check-previous@master
        with:
          workflow-name: Delivery
          github-token: ${{ secrets.github-token }}
