name: Build & push to ECR

# Builds an image using the project's Dockerfile, and pushes it
# to ECR (Elastic Container Registry) repository.

on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false
        default: latest
      repository-name:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: "eu-north-1"
    secrets:
      github-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      build-args:
        required: false

jobs:
  build:
    name: Build & push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: auth
        name: Authenticate to ECR and GHCR
        uses: dronetag/gha-shared/.github/actions/ecr-authenticate@master
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}
          github-token: ${{ secrets.github-token }}
      - id: list
        name: List output image tags
        env:
          TAGS: ${{ inputs.tags }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.repository-name }}
        run: |
          REPOSITORY_URI="$REGISTRY/$REPOSITORY"
          echo "::set-output name=tags::$(echo $TAGS | sed "s|[^ ]*|$REPOSITORY_URI\:&|g")" 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: ${{ secrets.build-args }}
          tags: ${{ steps.list.outputs.tags }}