name: Build & push to ECR

# Builds an image using the project's Dockerfile, and pushes it
# to ECR (Elastic Container Registry) repository.
# 
# Following three image tags will be pushed:
#  - {repositoryName}:{imageTag}
#  - {repositoryName}:{sha}
#  - {repositoryName}:latest

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      repository-name:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: "eu-north-1"
    secrets:
      github-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      build-args:
        required: false

jobs:
  build:
    name: Build & push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ inputs.awsRegion }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Authorize Docker to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.githubToken }}
      - name: Build & push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: ${{ secrets.buildArgs }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repositoryName }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repositoryName }}:${{ inputs.imageTag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repositoryName }}:latest