name: Update image on EKS

# A workflow to update images on EKS
#
# This updates image(s) on specified deployments (there might me more than just
# one) on EKS (Elastic Kubernetes Service) for the specified cluster

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      deployments:
        type: string
        required: true
      repository:
        type: string
        required: true
      cluster:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: "eu-north-1"
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  update-image:
    name: Update image on Kube cluster
    runs-on: ubuntu-20.04
    steps:
      - id: aws
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
      - name: Set-up kubectl
        uses: azure/setup-kubectl@v1
      - name: Get kubeconfig for cluster
        run: aws eks update-kubeconfig --region ${{ inputs.aws-region }} --name ${{ inputs.cluster }}
      - name: Deploy image(s) to cluster
        run: |
          export AWS_ID=${{ steps.aws.outputs.aws-account-id }}
          export ECR_URI="$AWS_ID.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com"
          export REPOSITORY_URI="$ECR_URI/${{ inputs.repository }}"
          export IMAGE="$REPOSITORY_URI:${{ inputs.version }}"
          for DEP in $(echo ${{ inputs.deployments }}); do
          kubectl set image deployment/$DEP $DEP=$IMAGE
          done 
