name: Update image on EKS

# Updates image(s) on deployments in EKS (Elastic Kubernetes Service) on a
# specified cluster

on:
  workflow_call:
    inputs:
      containers:
        type: string
        required: true
      repository:
        type: string
        required: true
      cluster:
        type: string
        required: true
      awsRegion:
        type: string
        required: false
        default: "eu-north-1"
    secrets:
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true

jobs:
  update-image:
    name: Update image on ${{ inputs.cluster }} cluster
    runs-on: ubuntu-latest
    steps:
      - id: aws
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ inputs.awsRegion }}
      - name: Set-up kubectl
        uses: azure/setup-kubectl@v1
      - name: Get kubeconfig for cluster
        run: aws eks update-kubeconfig --region ${{ inputs.awsRegion }} --name ${{ inputs.cluster }}
      - id: list
        name: List images to update
        env:
          CONTAINERS: ${{ inputs.containers }}
        run: |
          AWS_ID=${{ steps.aws.outputs.aws-account-id }}
          ECR_URI="$AWS_ID.dkr.ecr.${{ inputs.awsRegion }}.amazonaws.com"
          REPOSITORY_URI="$ECR_URI/${{ inputs.repository }}"

          VERSION=$(git describe --tags --exact-match ${{ github.sha }})
          IMAGE="$REPOSITORY_URI:$VERSION"

          echo "::set-output name=images::$(echo $CONTAINERS | sed "s|[^ ]*|&=$IMAGE|g")" 
      - name: Deploy image(s) to cluster
        run: kubectl set image deployments --all ${{ inputs.images }}