name: Run unit tests of a Poetry project

# Runs the pytest unit tests suite
#
# Assumes, that the `install-poetry-project.yml` was run previously and
# therefore the `build` artifact exists.

on:
  workflow_call:
    inputs:
      pythonVersion:
        required: false
        type: string
        default: "3.9"
      poetryVersion:
        required: false
        type: string
        default: "1.1.11"

jobs:
  test:
    name: Run unit test suite
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ env.pythonVersion }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.pythonVersion }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: ${{ inputs.poetryVersion }}
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: /tmp
      - run: tar -C ${{ github.workspace }} -xf /tmp/build.tar
      - name: Run the test suite
        run: poetry run pytest --color=yes --verbose --showlocals --disable-warnings --cov=live tests