name: Run pre-commit checks

# A workflow that runs all-files check using pre-commit
#
# Assumes, that the `install-poetry-project.yml` was run previously and
# therefore the `build` artifact exists.

on:
  workflow_call:
    inputs:
      pythonVersion:
        required: false
        type: string
        default: "3.9"
      poetryVersion:
        required: false
        type: string
        default: "1.1.11"

jobs:
  check:
    name: Run pre-commit checks on all files
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ inputs.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.pythonVersion }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: ${{ inputs.poetryVersion }}
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: /tmp
      - run: tar -C ${{ github.workspace }} -xf /tmp/build.tar
      - name: Run pre-commit checks
        run: poetry run pre-commit run --verbose --all-files