name: Promote current branch

# This workflow promotes currently delivered to a maturity branch.
# If set-up correctly, this workflow can be called from GitHub
# using workflow_dispatch and have succeeding deployment workflow running.

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  check:
    name: Check target branch ref
    runs-on: ubuntu-latest
    outputs:
      branch-sha: ${{ steps.rev-parse.outputs.sha }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: Checkout the target branch
        run: git checkout ${{ inputs.branch }}; git pull
      - id: rev-parse
        name: Determine target branch's ref
        run: |
          SHA=$(git rev-parse ${{ inputs.branch }})
          echo "::set-output name=sha::$SHA"
      - name: Fast-forward the branch (if necessary)
        run: |
          if [[ ${{ steps.rev-parse.outputs.sha }} == ${{ github.sha }} ]]
            then
          exit 0
          else
            git checkout ${{ inputs.branch }}
            git reset --hard ${{ github.sha }}
            git push
          fi
      - run: echo "\n${{ inputs.branch }} is on:\n $(git show --pretty=reference)"