name: Run semantic-release

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: "16"
    secrets:
      githubToken:
        required: true
    outputs:
      version:
        description: Released version (commit tag)
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.export.outputs.version }}
    steps:
      - name: Checkout repository (full-depth)
        uses: actions/checkout@v2
        with: { fetch-depth: 0 } # Required to determine version
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
        run: npx semantic-release
      - name: Export released version
        id: export
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
