name: Create a release on Sentry

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      url:
        required: true
      authToken:
        required: true
      organization:
        required: true
      project:
        required: true


jobs:
  create-sentry-release:
    name: Create release on Sentry
    runs-on: ubuntu-latest
    needs: [release-version]
    steps:
      - name: Checkout repository (full-depth)
        uses: actions/checkout@v2
        with: { fetch-depth: 0 } # Required for auto-commits
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: ${{ secrets.url }}
          SENTRY_AUTH_TOKEN: ${{ secrets.authToken }}
          SENTRY_ORG: ${{ secrets.organization }}
          SENTRY_PROJECT: ${{ secrets.project }}
        with:
          version: ${{ inputs.version }}